@echo off
echo Starting Garmin Health Dashboard Frontend...
cd frontend
echo Current directory: %CD%
echo Checking npm...
npm --version
echo Starting React app...
npm start
echo.
echo Press any key to close...
pause