from __future__ import annotations
from typing import Protocol, Optional, Sequence


class IStrengthRepository(Protocol):
    # Schema management
    def ensure_tables(self) -> None: ...

    # Muscle groups
    def list_muscle_groups(self) -> list[dict]: ...
    def upsert_muscle_groups(self, groups: Sequence[dict]) -> None: ...

    # Exercises
    def search_exercises(self, *, query: str | None, muscle_group_id: int | None) -> list[dict]: ...
    def list_exercises(self) -> list[dict]: ...
    def get_exercise(self, exercise_id: int) -> Optional[dict]: ...
    def upsert_exercises(self, exercises: Sequence[dict]) -> None: ...

    # Workouts (nested save/load)
    def create_workout(self, payload: dict) -> dict:
        """Insert workout_sessions + exercise_logs + exercise_sets in one transaction.
        Payload shape:
        {
          userId, startedAt(optional iso), name, notes, durationMinutes,
          exercises: [ { exerciseDefinitionId, order, notes, sets: [ {setNumber,reps,weight,rpe,isWarmup} ] } ]
        }
        Returns inserted structure with generated ids.
        """
        ...

    def get_workout(self, workout_id: int) -> Optional[dict]: ...
    def list_workouts(self, *, limit: int = 50, offset: int = 0, user_id: str | None = None) -> list[dict]: ...
    def delete_workout(self, workout_id: int) -> bool: ...

    # History helpers
    def last_exercise_log(self, exercise_definition_id: int, user_id: str) -> Optional[dict]: ...

__all__ = ["IStrengthRepository"]
